Repository app-sre/deployment-validation-operator, pull requests merged in 2021-12, with the labels that each got.

#124 Ensure metrics are deleted for resources in a deleted namespace
  pkg/controller/generic_reconciler.go
Labels: approved, lgtm

#127 change default memory limit
  deploy/openshift/operator.yaml
Labels: approved, lgtm

#128 fix memory unit for memory limit
  deploy/openshift/operator.yaml
Labels: approved, lgtm

#129 Less prometheus metrics
  cmd/manager/main.go
Labels: approved, lgtm

#131 gofmt
  cmd/manager/main.go
Labels: lgtm

#137 no dot imports
  pkg/prometheus/prometheus.go
Labels: approved

#125 Deploy grafana to custom namespace (DVO-24)
  README.md
  deploy/observability/grafana-config.yaml
  deploy/observability/grafana-dashboard-dvo.yaml
  deploy/observability/grafana-dashboards.yaml
  deploy/observability/grafana-datasources.yaml
  deploy/observability/grafana-route.yaml
  deploy/observability/grafana-service.yaml
  deploy/observability/grafana.yaml
  deploy/observability/operator-group.yaml
  deploy/observability/prometheus-subscription.yaml
  deploy/observability/prometheus.yaml
  deploy/observability/service-monitor.yaml
  deploy/observability/template.yaml
  deploy/openshift/cluster-role-binding.yaml
  deploy/openshift/role-binding.yaml
Labels: approved, lgtm

#126 expose minimal prometheus metrics (DVO-23)
  cmd/manager/main.go
  pkg/prometheus/prometheus.go
  pkg/validations/base_test.go
  pkg/validations/validation_engine.go
Labels: approved, lgtm

#138 add update-strategy to subscription
  README.md
  deploy/openshift/deployment-validation-operator-olm-with-polling.yaml
Labels: approved, lgtm

#139 Update deploy yaml to use 0.2.0
  deploy/openshift/operator.yaml
Labels: approved, lgtm
