Repository app-sre/deployment-validation-operator, pull requests merged in 2024-08, with the labels that each got.

#354 remove the e2e test that is not used
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-publish.sh
  go.mod
  go.sum
  internal/testing/client.go
  internal/testing/loader.go
  internal/testing/prom_client.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
Labels: approved, lgtm

#356 update boilerplate commit to fix the build
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
Labels: approved, lgtm

#357 DVO-224: Updating boilerplate to fix typo while building
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
Labels: approved, jira/valid-reference

#359 dependencies update
  go.mod
  go.sum
Labels: approved, lgtm

#360 bump up helm dependency version
  go.mod
  go.sum
Labels: approved, lgtm

#352 Format PipelineRun files and upload SAST results
  .tekton/deployment-validation-operator-pull-request.yaml
  .tekton/deployment-validation-operator-push.yaml
Labels: approved, lgtm, ok-to-test

#361 NO-JIRA: Fixed catalog prefix from boilerplate
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
Labels: approved, lgtm, jira/valid-reference

#365 add definition of done
  DoD.md
Labels: approved, lgtm
