Repository app-sre/deployment-validation-operator, pull requests merged in 2024-10, with the labels that each got.

#371 update the default CSV description
  deploy/bundle/template/deployment-validation-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#370 DVO-230: fix makefile for build tag job
  Makefile
  build/Dockerfile
  build/build_opm_catalog.sh
  build_tag.sh
  ci/codecov.sh
Labels: approved, do-not-merge/hold, lgtm, jira/valid-reference

#372 DVO-228: Move registry login to script
  Makefile
  build/build_opm_catalog.sh
Labels: approved, lgtm, jira/valid-reference

#373 DVO-228: Cleanup old dependency
  README.md
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/boilerplate-commit
  boilerplate/_lib/boilerplate.mk
  boilerplate/_lib/common.sh
  boilerplate/_lib/container-make
  boilerplate/_lib/freeze-check
  boilerplate/_lib/release.sh
  boilerplate/_lib/subscriber
  boilerplate/_lib/subscriber-propose
  boilerplate/_lib/subscriber-propose-update
  boilerplate/_lib/subscriber-report
  boilerplate/_lib/subscriber-report-onboarding
  boilerplate/_lib/subscriber-report-pr
  boilerplate/_lib/subscriber-report-release
  boilerplate/_lib/subscriber.sh
  boilerplate/generated-includes.mk
  boilerplate/openshift/golang-osd-operator/.ci-operator.yaml
  boilerplate/openshift/golang-osd-operator/.codecov.yml
  boilerplate/openshift/golang-osd-operator/Dockerfile.olm-registry
  boilerplate/openshift/golang-osd-operator/OWNERS_ALIASES
  boilerplate/openshift/golang-osd-operator/README.md
  boilerplate/openshift/golang-osd-operator/app-sre-build-deploy.sh
  boilerplate/openshift/golang-osd-operator/app-sre.md
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
  boilerplate/openshift/golang-osd-operator/codecov.sh
  boilerplate/openshift/golang-osd-operator/configure-fips.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-build.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-publish.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/common-generate-operator-bundle.py
  boilerplate/openshift/golang-osd-operator/csv-generate/common.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.mk
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.sh
  boilerplate/openshift/golang-osd-operator/dependabot.yml
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/fips.go.tmplt
  boilerplate/openshift/golang-osd-operator/golangci.yml
  boilerplate/openshift/golang-osd-operator/project.mk
  boilerplate/openshift/golang-osd-operator/prow-config
  boilerplate/openshift/golang-osd-operator/py-requirements.txt
  boilerplate/openshift/golang-osd-operator/rvmo-bundle.sh
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/openshift/golang-osd-operator/update
  boilerplate/openshift/golang-osd-operator/validate-yaml.py
  boilerplate/update
  boilerplate/update.cfg
  build/Dockerfile.test
Labels: approved, lgtm
