Repository app-sre/deployment-validation-operator, pull requests merged in 2024-07, with the labels that each got.

#345 Bump up boilerplate version
  .ci-operator.yaml
  OWNERS_ALIASES
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/common.sh
  boilerplate/openshift/golang-osd-operator/Dockerfile.olm-registry
  boilerplate/openshift/golang-osd-operator/OWNERS_ALIASES
  boilerplate/openshift/golang-osd-operator/app-sre-build-deploy.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-build.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-publish.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/common-generate-operator-bundle.py
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.mk
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.sh
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/golangci.yml
  boilerplate/openshift/golang-osd-operator/project.mk
  boilerplate/openshift/golang-osd-operator/rvmo-bundle.sh
  boilerplate/openshift/golang-osd-operator/standard.mk
  build/Dockerfile
  build/Dockerfile.olm-registry
Labels: approved, do-not-merge/invalid-owners-file

#346 bump up controller-runtime version
  go.mod
  go.sum
Labels: approved, lgtm

#348 DVO-224 trying to fix failing build
  Makefile
Labels: approved

#349 DVO-224: additional commit
  Makefile
Labels: approved, jira/valid-reference

#350 reverting my last commits and trying another approach for DVO-224
  Makefile
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved

#351 another boilerplate update
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
Labels: approved

#355 OSD-24739 / DVO-223: Making sure DVO is deployed/updated on all hosted clusters
  hack/olm-registry/hypershift-template.yaml
Labels: approved, lgtm, ok-to-test, jira/valid-reference
