Repository app-sre/deployment-validation-operator, pull requests merged in 2025-04, with the labels that each got.

#461 DVO-231: Fix outdated CI builder image
  .ci-operator.yaml
  .gitattributes
  .github/dependabot.yml
  Makefile
  ci/golangci-lint.sh
Labels: approved, jira/valid-reference

#442 DVO-213: Test hermetic build consolidation
  .tekton/deployment-validation-operator-bundle-pull-request.yaml
  .tekton/deployment-validation-operator-bundle-push.yaml
  .tekton/deployment-validation-operator-pull-request.yaml
  .tekton/deployment-validation-operator-push.yaml
  konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#477 NO-JIRA: Add configuration for konflux-bot
  renovate.json
Labels: approved, jira/valid-reference

#480 NO-JIRA: Bump Golang to 1.23
  go.mod
Labels: approved, jira/valid-reference

#483 Update the Golang version of .ci-operator.yaml
  .ci-operator.yaml
Labels: approved, lgtm

#484 Add go mod tidy to avoid some errors at build time
  Makefile
Labels: approved, lgtm

#485 Revert unneeded tidy command
  Makefile
Labels: approved, lgtm

#486 DVO-213: Add ImageDigestMirrorSet links
  .tekton/deployment-validation-operator-fbc-pull-request.yaml
  .tekton/deployment-validation-operator-fbc-push.yaml
  .tekton/images-mirror-set.yaml
  konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml
  konflux-ci/staging-release.yaml
  konflux-ci/staging-snapshot.yaml
Labels: approved, lgtm, jira/valid-reference
