Repository app-sre/deployment-validation-operator, pull requests merged in 2025-02, with the labels that each got.

#416 SDCICD-1436: set securityContextConfig restricted
  hack/olm-registry/hypershift-template.yaml
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#413 NO-JIRA: Update dependencies versions on some libraries
  build/Dockerfile
  go.mod
  go.sum
  konflux-ci/bundle/bundle.Dockerfile
  konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#417 DVO-213: add staging manifests
  konflux-ci/release-snapshot.yaml
  konflux-ci/release-staging.yaml
Labels: approved, lgtm, jira/valid-reference

#420 Fix fips enablement tags
  Makefile
Labels: approved, lgtm, ok-to-test

#419 NO-JIRA: Add new team members
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#422 NO-JIRA: Add missing labels on bundle image
  konflux-ci/bundle/bundle.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#423 NO-JIRA: Update Bundle image annotations and fixing a label
  konflux-ci/bundle/bundle.Dockerfile
  konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#418 DVO-241: Fix builder image to a valid-Konflux compliant one
  build/Dockerfile
Labels: approved, lgtm, jira/valid-reference
