Repository app-sre/deployment-validation-operator, pull requests merged in 2025-07, with the labels that each got.

#522 NO-JIRA: Updating CI base image to support Golang with 1.24
  .ci-operator.yaml
Labels: approved, lgtm, jira/valid-reference

#530 DVO-285: Konflux FBC release pipeline fix
  konflux-ci/fbc/catalog/deployment-validation-operator/catalog.yml
Labels: approved, jira/valid-reference

#531 NO-JIRA: Fix images typos from dependabot
  build/Dockerfile
Labels: approved, lgtm, jira/valid-reference

#509 DVO-283: Update minimum Golang version
  go.mod
Labels: approved, lgtm, jira/valid-reference

#540 Add missing digest to operator image
  konflux-ci/fbc/bundle.object/catalog/deployment-validation-operator/catalog.yml
  konflux-ci/fbc/csv.metadata/catalog/deployment-validation-operator/catalog.yml
Labels: approved

#541 Fix missing annotation digest appears to break building process
  konflux-ci/fbc/csv.metadata/catalog/deployment-validation-operator/catalog.yml
Labels: approved

#545 NO-JIRA: Maintenance : update golang 1.24
  build/Dockerfile
  go.mod
  go.sum
Labels: approved, jira/valid-reference
